-- Your SQL goes here
CREATE TABLE 'students' (
    'register' INTEGER UNIQUE NOT NULL PRIMARY KEY,
    'fullname' VARCHAR(255) NOT NULL,
    'type' VARCHAR(255) NOT NULL,
    'status' VARCHAR(255) NOT NULL,
    'semester' VARCHAR(255) NOT NULL,
    'group' VARCHAR(255) NOT NULL,
    'turn' VARCHAR(255) NOT NULL,
    'level' VARCHAR(255) NOT NULL,
    'created_at' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    'updated_at' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);